#!/usr/bin/env bash
# infra/testnet/host/setup-host.sh -- configure one M1 testnet host for its
# role. Run as root by deploy.sh (never by hand on a laptop). Idempotent:
# re-running converges, and is how binaries are upgraded (new tag in
# host.env) and how the epoch base / bootnodes are rolled out.
#
#   setup-host.sh <host.env>               full setup
#   setup-host.sh <host.env> --enode-only  node key + enode only
#   setup-host.sh <host.env> --render DIR  write the files this host would
#                                          get (/etc/sova/*, units) under
#                                          DIR and stop: no root, no
#                                          network, runs on a laptop
#                                          (deploy.sh render uses it)
#
# host.env (generated by deploy.sh, nothing secret) sets ROLE and the
# config.env values below. Roles:
#   seed   zebrad (inbound 18233) + sova-node follow-only, P2P inbound
#   rpc    zebrad + sova-node follow-only (public RPC profile) + cloudflared
#   faucet zebrad + sova-faucet (own hot key) + cloudflared
#   keeper zebrad + sova-node in MINE mode (seals, incl. null blocks;
#          with SOVA_SIP6=1 it signs as the keeper's miner key)
#          + sova-keeper burner (installed, not started)
#
# SOVA_SIP6=1 (the default): every node requires SIP-6 sealed or null
# blocks, and the keeper's node signs with a 0600 copy of the keeper's
# sova-miner keystore owned by the node's user (sova), at
# /var/lib/sova/sealer/keystore.json. Its seal journal lives under the
# persistent SOVA_DATADIR (/var/lib/sova/node/seal-journal/<address>).
#
# Lines starting "KIT-OUT " are machine-read by deploy.sh (enode, faucet
# t-addr, keeper addresses: all public).
set -euo pipefail

ENV_FILE="${1:?usage: setup-host.sh <host.env>}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "${ENV_FILE}"

: "${ROLE:?}" "${PUBLIC_IPV4:?}" "${SOVA_RELEASE_TAG:?}" "${SOVA_RELEASE_REPO:?}"
: "${ZEBRA_IMAGE:?}" "${SOVA_P2P_PORT:?}" "${ZEBRA_P2P_PORT:?}" "${ZEBRA_RPC_PORT:?}"
: "${SOVA_HTTP_PORT:?}" "${SOVA_AUTH_PORT:?}" "${FAUCET_PORT:?}"
SOVA_EPOCH_BASE="${SOVA_EPOCH_BASE:-}"
SOVA_BOOTNODES="${SOVA_BOOTNODES:-}"
SOVA_EMISSION_SCHEDULE="${SOVA_EMISSION_SCHEDULE:-sip3}"
SOVA_SIP6="${SOVA_SIP6:-1}"
BUILD_FROM_SOURCE="${BUILD_FROM_SOURCE:-0}"

DATA=/var/lib/sova
ETC=/etc/sova
# SIP-6: the keeper node's sealing key, a copy of the keeper's miner
# keystore readable only by the node's user (sova-node.service User=sova).
SEALER_KEYSTORE="${DATA}/sealer/keystore.json"
UNIT_DIR=/etc/systemd/system
RENDER=""
if [[ "${2:-}" == --render ]]; then
  RENDER="${3:?--render needs a directory}"
  ETC="${RENDER}/etc/sova"
  UNIT_DIR="${RENDER}/etc/systemd/system"
fi
PLATFORM=linux-x86_64
ASSET="sova-box-bin-${PLATFORM}.tar.gz"

log() { printf '[setup-host %s] %s\n' "${ROLE}" "$*"; }
die() {
  printf '[setup-host %s] error: %s\n' "${ROLE}" "$*" >&2
  exit 1
}
# To stderr, so it survives command substitution; deploy.sh reads 2>&1.
out() { printf 'KIT-OUT %s %s\n' "$1" "$2" >&2; }

if [[ -z "${RENDER}" ]]; then
  [[ "$(id -u)" == 0 ]] || die "run as root"
  [[ "$(uname -m)" == x86_64 ]] || die "x86_64 only (the release ships ${PLATFORM})"
  # shellcheck source=/dev/null
  . /etc/os-release
  [[ "${ID}" == ubuntu ]] || die "Ubuntu expected, got ${ID}"
fi
case "${ROLE}" in seed | rpc | faucet | keeper) ;; *) die "unknown ROLE ${ROLE}" ;; esac
[[ -z "${SOVA_EPOCH_BASE}" || "${SOVA_EPOCH_BASE}" =~ ^[1-9][0-9]*$ ]] || die "SOVA_EPOCH_BASE must be a positive integer"
case "${SOVA_EMISSION_SCHEDULE}" in sip3 | flat) ;; *) die "SOVA_EMISSION_SCHEDULE must be sip3 or flat" ;; esac
case "${SOVA_SIP6}" in 0 | 1) ;; *) die "SOVA_SIP6 must be 0 or 1" ;; esac

has_node() { [[ "${ROLE}" == seed || "${ROLE}" == rpc || "${ROLE}" == keeper ]]; }
has_tunnel() { [[ "${ROLE}" == rpc || "${ROLE}" == faucet ]]; }

# ---- data volume ----------------------------------------------------------------
mount_volume() {
  local devs=() d uuid
  for d in /dev/disk/by-id/scsi-0HC_Volume_*; do [[ -e "${d}" ]] && devs+=("${d}"); done
  mkdir -p "${DATA}"
  if [[ ${#devs[@]} -eq 0 ]]; then
    # Also the normal case on an (optional) byo host, e.g. an AWS keeper
    # with one 40 GB gp3 root volume.
    log "no Hetzner volume attached; state lives on the root disk"
    return 0
  fi
  [[ ${#devs[@]} -eq 1 ]] || die "expected one attached volume, found ${#devs[@]}"
  uuid="$(blkid -s UUID -o value "${devs[0]}")" || die "volume ${devs[0]} has no filesystem (provision.sh formats it ext4)"
  if ! grep -q "UUID=${uuid}" /etc/fstab; then
    echo "UUID=${uuid} ${DATA} ext4 defaults,discard,nofail 0 2" >>/etc/fstab
  fi
  mountpoint -q "${DATA}" || mount "${DATA}"
  log "data volume ${devs[0]} mounted at ${DATA}"
}

# ---- users and directories --------------------------------------------------------
ensure_user() { # name [uid]
  if ! id -u "$1" >/dev/null 2>&1; then
    if [[ -n "${2:-}" ]]; then
      groupadd --system --gid "$2" "$1"
      useradd --system --uid "$2" --gid "$2" --home-dir /nonexistent --shell /usr/sbin/nologin "$1"
    else
      useradd --system --user-group --home-dir /nonexistent --shell /usr/sbin/nologin "$1"
    fi
  fi
}

setup_dirs() {
  # The zfnd/zebra image runs zebrad as uid/gid 10001.
  ensure_user zebra 10001
  install -d -m 0750 -o 10001 -g 10001 "${DATA}/zebrad"
  install -d -m 0755 "${ETC}" /usr/local/lib/sova-infra
  if has_node; then
    ensure_user sova
    install -d -m 0700 -o sova -g sova "${DATA}/node" "${DATA}/node/tmp"
  fi
  if [[ "${ROLE}" == faucet ]]; then
    ensure_user sova-faucet
    install -d -m 0700 -o sova-faucet -g sova-faucet "${DATA}/faucet"
  fi
  if [[ "${ROLE}" == keeper ]]; then
    ensure_user sova-keeper
    install -d -m 0700 -o sova-keeper -g sova-keeper "${DATA}/keeper"
  fi
}

# ---- host firewall (mirrors the Hetzner firewall / a byo host's security group;
# defence in depth) -----------------------------------------------------------------
setup_ufw() {
  ufw default deny incoming >/dev/null
  ufw default allow outgoing >/dev/null
  ufw allow 22/tcp >/dev/null
  if [[ "${ROLE}" == seed ]]; then
    ufw allow "${SOVA_P2P_PORT}/tcp" >/dev/null
    ufw allow "${SOVA_P2P_PORT}/udp" >/dev/null
    ufw allow "${ZEBRA_P2P_PORT}/tcp" >/dev/null
  fi
  ufw --force enable >/dev/null
  log "ufw: $(ufw status | grep -c ALLOW) allow rule(s)"
}

# ---- zebrad -------------------------------------------------------------------------
zebra_ref() {
  local ref="${ZEBRA_IMAGE}"
  [[ -n "${ZEBRA_IMAGE_DIGEST:-}" ]] && ref="${ZEBRA_IMAGE}@${ZEBRA_IMAGE_DIGEST}"
  printf '%s' "${ref}"
}

write_zebrad_files() { # image-ref
  printf 'ZEBRA_IMAGE_REF=%s\n' "$1" >"${ETC}/zebrad.env"
  sed -e "s/@ZEBRA_P2P_PORT@/${ZEBRA_P2P_PORT}/" -e "s/@ZEBRA_RPC_PORT@/${ZEBRA_RPC_PORT}/" \
    "${HERE}/zebrad.toml" >"${ETC}/zebrad.toml"
  chmod 0644 "${ETC}/zebrad.toml"
}

setup_zebrad() {
  local ref
  ref="$(zebra_ref)"
  docker pull -q "${ref}" >/dev/null || die "docker pull ${ref} failed"
  write_zebrad_files "${ref}"
  install -m 0644 "${HERE}/systemd/zebrad.service" "${UNIT_DIR}/zebrad.service"
  systemctl daemon-reload
  systemctl enable zebrad >/dev/null 2>&1
  # Restart only if the image or config changed (a restart costs a
  # RocksDB reopen, not a resync).
  local sum
  sum="$(cat "${ETC}/zebrad.env" "${ETC}/zebrad.toml" | sha256sum | cut -d' ' -f1)"
  if [[ "$(cat "${ETC}/.zebrad.sum" 2>/dev/null)" != "${sum}" ]] || ! systemctl is-active --quiet zebrad; then
    systemctl restart zebrad
    echo "${sum}" >"${ETC}/.zebrad.sum"
    log "zebrad (re)started with ${ref}"
  else
    log "zebrad unchanged and running"
  fi
}

# ---- binaries: tagged GitHub Release, SHA256SUMS verified -------------------------
# Same checks as box/up.sh's fetch_prebuilt_from_release/verify_prebuilt:
# release-level SHA256SUMS over the tarball, release BUILD-INFO names the
# tag and platform, the tarball's own SHA256SUMS over both binaries, and
# the tarball's BUILD-INFO commit equals the release's.
RELEASE_COMMIT=""
install_release_binaries() {
  local dest="/usr/local/lib/sova/${SOVA_RELEASE_TAG}"
  if [[ -x "${dest}/sova" && -x "${dest}/sova-miner" && -s "${dest}/COMMIT" ]]; then
    RELEASE_COMMIT="$(cat "${dest}/COMMIT")"
    log "release ${SOVA_RELEASE_TAG} already installed (${RELEASE_COMMIT:0:12})"
    return 0
  fi
  local tmp base expected actual rel_tag rel_platforms inner_commit inner_platform f
  tmp="$(mktemp -d)"
  base="https://github.com/${SOVA_RELEASE_REPO}/releases/download/${SOVA_RELEASE_TAG}"
  for f in SHA256SUMS BUILD-INFO "${ASSET}"; do
    curl -fsSL --retry 3 -o "${tmp}/${f}" "${base}/${f}" || {
      rm -rf "${tmp}"
      return 1
    }
  done
  expected="$(awk -v n="${ASSET}" '$2 == n || $2 == ("*" n) { print $1; exit }' "${tmp}/SHA256SUMS")"
  actual="$(sha256sum "${tmp}/${ASSET}" | cut -d' ' -f1)"
  [[ -n "${expected}" && "${expected}" == "${actual}" ]] || die "release ${ASSET}: SHA-256 mismatch (SHA256SUMS '${expected:0:12}', got '${actual:0:12}')"
  rel_tag="$(sed -n 's/^tag=//p' "${tmp}/BUILD-INFO")"
  rel_platforms="$(sed -n 's/^platforms=//p' "${tmp}/BUILD-INFO")"
  RELEASE_COMMIT="$(sed -n 's/^commit=//p' "${tmp}/BUILD-INFO")"
  [[ "${rel_tag}" == "${SOVA_RELEASE_TAG}" ]] || die "release BUILD-INFO names tag '${rel_tag}', expected ${SOVA_RELEASE_TAG}"
  [[ " ${rel_platforms} " == *" ${PLATFORM} "* ]] || die "release does not list ${PLATFORM}"
  mkdir -p "${tmp}/x"
  tar -xzf "${tmp}/${ASSET}" -C "${tmp}/x" sova sova-miner SHA256SUMS BUILD-INFO ||
    die "${ASSET} does not unpack to sova, sova-miner, SHA256SUMS, BUILD-INFO"
  (cd "${tmp}/x" && sha256sum -c --quiet SHA256SUMS) || die "tarball SHA256SUMS check failed"
  inner_commit="$(sed -n 's/^commit=//p' "${tmp}/x/BUILD-INFO")"
  inner_platform="$(sed -n 's/^platform=//p' "${tmp}/x/BUILD-INFO")"
  [[ "${inner_commit}" == "${RELEASE_COMMIT}" ]] || die "tarball commit ${inner_commit} != release commit ${RELEASE_COMMIT}"
  [[ "${inner_platform}" == "${PLATFORM}" ]] || die "tarball is for ${inner_platform}"
  install -d "${dest}"
  install -m 0755 "${tmp}/x/sova" "${tmp}/x/sova-miner" "${dest}/"
  install -m 0644 "${tmp}/x/SHA256SUMS" "${tmp}/x/BUILD-INFO" "${dest}/"
  echo "${RELEASE_COMMIT}" >"${dest}/COMMIT"
  rm -rf "${tmp}"
  log "installed release ${SOVA_RELEASE_TAG} (${RELEASE_COMMIT:0:12}), SHA256SUMS verified"
}

# Source build (the faucet always; everything with BUILD_FROM_SOURCE=1).
# Checks the tag's commit against the release's when there is one.
SRC=""
ensure_source() {
  [[ -n "${SRC}" ]] && return 0
  apt-get update -qq && apt-get install -y -qq build-essential pkg-config clang >/dev/null
  ensure_user sova-build
  install -d -m 0755 -o sova-build -g sova-build "${DATA}/build"
  local home="${DATA}/build"
  if [[ ! -x "${home}/.cargo/bin/cargo" ]]; then
    sudo -u sova-build HOME="${home}" sh -c \
      'curl -fsSL https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable' >/dev/null
  fi
  SRC="${home}/src-${SOVA_RELEASE_TAG}"
  if [[ ! -d "${SRC}/.git" ]]; then
    sudo -u sova-build git clone -q --depth 1 --branch "${SOVA_RELEASE_TAG}" "${SOVA_SOURCE_REPO_URL}" "${SRC}"
  fi
  local head
  head="$(sudo -u sova-build git -C "${SRC}" rev-parse HEAD)"
  if [[ -n "${RELEASE_COMMIT}" && "${head}" != "${RELEASE_COMMIT}" ]]; then
    die "tag ${SOVA_RELEASE_TAG} is ${head} in ${SOVA_SOURCE_REPO_URL}, but the release was built from ${RELEASE_COMMIT}"
  fi
  log "source ${SOVA_RELEASE_TAG} at ${head:0:12}"
}

cargo_build() { # cargo args...
  sudo -u sova-build HOME="${DATA}/build" CARGO_TARGET_DIR="${DATA}/build/target" \
    sh -c 'cd "$0" && "$HOME/.cargo/bin/cargo" build --release --locked "$@"' "${SRC}" "$@"
}

install_binaries() {
  local dest="/usr/local/lib/sova/${SOVA_RELEASE_TAG}"
  if [[ "${BUILD_FROM_SOURCE}" == 1 ]] || ! install_release_binaries; then
    [[ "${BUILD_FROM_SOURCE}" == 1 ]] || log "release download failed; building from source (slow: reth, ~20-40 min)"
    ensure_source
    cargo_build -p sova
    cargo_build -p sova-miner --manifest-path crates/burn-wallet/Cargo.toml
    install -d "${dest}"
    install -m 0755 "${DATA}/build/target/release/sova" "${DATA}/build/target/release/sova-miner" "${dest}/"
    # shellcheck disable=SC2024 # root writes the file; git runs as the build user
    sudo -u sova-build git -C "${SRC}" rev-parse HEAD >"${dest}/COMMIT"
  fi
  if [[ "${ROLE}" == faucet && ! -x "${dest}/sova-faucet" ]]; then
    # Not in the release tarball; the burn-wallet workspace doesn't link
    # reth, so this is a few minutes.
    ensure_source
    cargo_build -p sova-faucet --manifest-path crates/burn-wallet/Cargo.toml
    install -m 0755 "${DATA}/build/target/release/sova-faucet" "${dest}/"
  fi
  local b
  for b in sova sova-miner sova-faucet; do
    [[ -x "${dest}/${b}" ]] && ln -sfn "${dest}/${b}" "/usr/local/bin/${b}"
  done
  echo "${SOVA_RELEASE_TAG}" >"${ETC}/release"
}

# ---- sova node ----------------------------------------------------------------------
node_key_and_enode() {
  local key="${DATA}/node/discovery-secret"
  if [[ ! -s "${key}" ]]; then
    # Pre-generated so the enode is known before the first start, and
    # stable across restarts (SOVA_DATADIR). reth parses exactly 64 hex
    # chars: no trailing newline.
    (umask 077 && openssl rand -hex 32 | tr -d '\n' >"${key}")
    chown sova:sova "${key}"
  fi
  chmod 0600 "${key}"
  local enode
  enode="$(python3 "${HERE}/enode.py" "${key}" "${PUBLIC_IPV4}" "${SOVA_P2P_PORT}")"
  echo "${enode}" >"${ETC}/enode"
  out enode "${enode}"
}

# No SOVA_RPC_CORS here on purpose: every host's RPC binds 127.0.0.1, and
# the only browser-facing path is rpc.<domain> through the edge Worker
# (worker/rpc-firewall.mjs), which answers CORS itself.
node_env_text() { # mode-lines rpc-profile
  cat <<EOF
# Written by setup-host.sh (${ROLE}); re-run deploy.sh to change it.
SOVA_CHAIN=sova-testnet
SOVA_GOSSIP=p2p
$1
SOVA_ZEBRAD_RPC=http://127.0.0.1:${ZEBRA_RPC_PORT}
SOVA_EPOCH_BASE=${SOVA_EPOCH_BASE}
SOVA_EMISSION_SCHEDULE=${SOVA_EMISSION_SCHEDULE}
SOVA_SIP6=${SOVA_SIP6}
SOVA_DATADIR=${DATA}/node
SOVA_BOOTNODES=${SOVA_BOOTNODES}
SOVA_P2P_PORT=${SOVA_P2P_PORT}
SOVA_NAT=extip:${PUBLIC_IPV4}
SOVA_HTTP_PORT=${SOVA_HTTP_PORT}
SOVA_AUTH_PORT=${SOVA_AUTH_PORT}
SOVA_RPC_PROFILE=$2
RUST_LOG=info
RUST_LOG_STYLE=never
NO_COLOR=1
EOF
}

setup_node() {
  node_key_and_enode

  local mode_lines rpc_profile=public
  if [[ "${ROLE}" == keeper ]]; then
    # Mine mode: seals its own burns' epochs, and null blocks (SIP-6
    # §2.4; rewardless cadence blocks with SIP-6 off) for burn-less
    # epochs, so the chain has a producer on day 1. It is an ordinary
    # sealer with no privilege (D8). With SIP-6 it signs as the keeper's
    # miner key and journals under SOVA_DATADIR (persistent).
    local evm
    evm="$(keeper_evm_address)"
    mode_lines="$(keeper_mode_lines "${evm}")"
    rpc_profile=local
  else
    mode_lines="SOVA_FOLLOW_ONLY=1"
  fi
  local changed=0
  if [[ "${ROLE}" == keeper && "${SOVA_SIP6}" == 1 ]]; then
    install_sealer_key
    [[ ${SEALER_KEY_CHANGED} == 0 ]] || changed=1
  fi
  node_env_text "${mode_lines}" "${rpc_profile}" >"${ETC}/sova-node.env.new"
  if ! cmp -s "${ETC}/sova-node.env.new" "${ETC}/sova-node.env"; then
    mv "${ETC}/sova-node.env.new" "${ETC}/sova-node.env"
    changed=1
  else
    rm -f "${ETC}/sova-node.env.new"
  fi
  chmod 0644 "${ETC}/sova-node.env"
  install -m 0644 "${HERE}/systemd/sova-node.service" "${UNIT_DIR}/sova-node.service"
  systemctl daemon-reload
  systemctl enable sova-node >/dev/null 2>&1
  if [[ -z "${SOVA_EPOCH_BASE}" ]]; then
    rm -f "${ETC}/epoch-base-pinned"
    systemctl stop sova-node 2>/dev/null || true
    log "sova-node installed, NOT started: SOVA_EPOCH_BASE is not pinned yet (runbook: Pin B)"
    return 0
  fi
  echo "${SOVA_EPOCH_BASE}" >"${ETC}/epoch-base-pinned"
  local bin_changed=0
  [[ "$(readlink /usr/local/bin/sova)" != "$(cat "${ETC}/.sova-node.bin" 2>/dev/null)" ]] && bin_changed=1
  if [[ ${changed} == 1 || ${bin_changed} == 1 ]] || ! systemctl is-active --quiet sova-node; then
    systemctl restart sova-node
    readlink /usr/local/bin/sova >"${ETC}/.sova-node.bin"
    log "sova-node (re)started (epoch base ${SOVA_EPOCH_BASE}, ${SOVA_EMISSION_SCHEDULE}, SIP-6 $([[ "${SOVA_SIP6}" == 1 ]] && echo on || echo off))"
  else
    log "sova-node unchanged and running"
  fi
}

# ---- faucet ----------------------------------------------------------------------------
faucet_toml_text() {
  cat <<EOF
# Written by setup-host.sh. Defaults from
# crates/burn-wallet/faucet/faucet.example.toml; docs/ops/faucet.md.
network = "test"
listen = "127.0.0.1:${FAUCET_PORT}"
zebrad_rpc = "http://127.0.0.1:${ZEBRA_RPC_PORT}"
keystore = "${DATA}/faucet/keystore.json"
state_file = "${DATA}/faucet/state.json"
drip_zat = 10000000
address_cooldown_secs = 86400
ip_cooldown_secs = 86400
daily_cap_zat = 200000000
max_balance_multiple = 5
# cloudflared on this host is the only socket peer; believe its header.
trusted_proxy_header = "CF-Connecting-IP"
trusted_proxy_peers = ["127.0.0.1", "::1"]
status_cache_secs = 10
EOF
}

setup_faucet() {
  faucet_toml_text >"${ETC}/faucet.toml"
  chmod 0644 "${ETC}/faucet.toml"
  if [[ ! -s "${DATA}/faucet/keystore.json" ]]; then
    # The one hot key (D5). Created here, never copied anywhere; a rebuild
    # makes a new one (rotate = init again + fund the new address).
    sudo -u sova-faucet /usr/local/bin/sova-faucet init --keystore "${DATA}/faucet/keystore.json" --network test >/dev/null
  fi
  out faucet_taddr "$(sudo -u sova-faucet /usr/local/bin/sova-faucet address --config "${ETC}/faucet.toml")"
  install -m 0644 "${HERE}/systemd/sova-faucet.service" "${UNIT_DIR}/sova-faucet.service"
  systemctl daemon-reload
  systemctl enable sova-faucet >/dev/null 2>&1
  systemctl restart sova-faucet
  log "faucet running on 127.0.0.1:${FAUCET_PORT} (fund the t-addr with a plain transfer)"
}

# ---- keeper ----------------------------------------------------------------------------
keeper_evm_address() {
  local init
  # stdout + stderr: the legacy-address warning goes to stderr.
  init="$(sudo -u sova-keeper /usr/local/bin/sova-miner --network test --data-dir "${DATA}/keeper" init 2>&1)"
  if [[ "${SOVA_SIP6}" == 1 ]] && grep -qE "LEGACY|not this key's own" <<<"${init}"; then
    # SIP-6 seals with the keystore key, so burns must credit that key's
    # own address. bin/sova would refuse the mismatch at start; fail here
    # first, with the fix. A fresh init always credits the key's own.
    printf '%s\n' "${init}" >&2
    die "the keeper's burns do not credit its own key's EVM address; SIP-6 needs them to (run: sudo -u sova-keeper sova-miner --network test --data-dir ${DATA}/keeper init --migrate-evm-address, then re-run deploy.sh; docs/ops/keeper-miner.md)"
  fi
  out keeper_taddr "$(awk '/t-addr to fund/ {print $NF}' <<<"${init}")"
  local evm
  evm="$(awk '/evm address/ {print $NF}' <<<"${init}")"
  out keeper_evm "${evm}"
  [[ "${evm}" =~ ^0x[0-9a-fA-F]{40}$ ]] || die "could not read the keeper's EVM address from sova-miner init"
  echo "${evm}"
}

# The keeper node's mode lines. SOVA_MINER_EVM_ADDRESS stays (it is what
# `sova-miner init` reports the burns credit): with SIP-6 on, bin/sova
# refuses to start unless it equals the sealing key's address, so the
# node can never seal as one address while burning for another.
keeper_mode_lines() { # evm
  printf 'SOVA_MINER_EVM_ADDRESS=%s\n' "$1"
  [[ "${SOVA_SIP6}" == 1 ]] && printf 'SOVA_SEALER_KEYSTORE=%s\n' "${SEALER_KEYSTORE}"
  return 0
}

# SIP-6: copy the keeper's miner keystore (sova-keeper's own 0600 file,
# which the burner keeps using) to the node's copy, 0600 and owned by sova,
# in a 0700 directory. Two files, each readable by exactly one service
# user. SEALER_KEY_CHANGED=1 if the copy changed (first install, or a
# re-init / migrate of the miner keystore), so the node restarts.
SEALER_KEY_CHANGED=0
install_sealer_key() {
  local src="${DATA}/keeper/keystore.json"
  [[ -s "${src}" ]] || die "no keeper keystore at ${src} (sova-miner init failed?)"
  install -d -m 0700 -o sova -g sova "$(dirname "${SEALER_KEYSTORE}")"
  if ! cmp -s "${src}" "${SEALER_KEYSTORE}"; then
    (umask 077 && install -m 0600 -o sova -g sova "${src}" "${SEALER_KEYSTORE}.new")
    mv -f "${SEALER_KEYSTORE}.new" "${SEALER_KEYSTORE}"
    SEALER_KEY_CHANGED=1
    log "sealing key installed at ${SEALER_KEYSTORE} (0600, sova)"
  fi
  chown sova:sova "${SEALER_KEYSTORE}"
  chmod 0600 "${SEALER_KEYSTORE}"
}

keeper_env_text() {
  cat <<EOF
ZEBRA_RPC_PORT=${ZEBRA_RPC_PORT}
KEEPER_PER_EPOCH_ZAT=${KEEPER_PER_EPOCH_ZAT:-10000}
KEEPER_BUDGET_ZAT=${KEEPER_BUDGET_ZAT:-35000000}
KEEPER_LIFETIME_BUDGET_ZAT=${KEEPER_LIFETIME_BUDGET_ZAT:-1000000000}
EOF
}

setup_keeper() {
  keeper_env_text >"${ETC}/keeper.env"
  install -m 0644 "${HERE}/systemd/sova-keeper.service" "${UNIT_DIR}/sova-keeper.service"
  systemctl daemon-reload
  log "sova-keeper installed, NOT started (publish the disclosure and fund the t-addr first; docs/ops/keeper-miner.md)"
}

# ---- cloudflared --------------------------------------------------------------------------
setup_cloudflared() {
  if ! command -v cloudflared >/dev/null 2>&1; then
    install -d -m 0755 /usr/share/keyrings
    curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg -o /usr/share/keyrings/cloudflare-main.gpg
    echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared ${VERSION_CODENAME} main" \
      >/etc/apt/sources.list.d/cloudflared.list
    apt-get update -qq && apt-get install -y -qq cloudflared >/dev/null
  fi
  install -m 0644 "${HERE}/systemd/cloudflared.service" "${UNIT_DIR}/cloudflared.service"
  systemctl daemon-reload
  systemctl enable cloudflared >/dev/null 2>&1
  if [[ -f "${ETC}/cloudflared.env" ]]; then
    systemctl restart cloudflared
    log "cloudflared running"
  else
    log "cloudflared installed; waiting for its token (cloudflare.sh tunnels)"
  fi
}

# ---- health ---------------------------------------------------------------------------------
health_env_text() {
  cat <<EOF
ROLE=${ROLE}
SOVA_EPOCH_BASE=${SOVA_EPOCH_BASE}
ZEBRA_RPC_PORT=${ZEBRA_RPC_PORT}
SOVA_HTTP_PORT=${SOVA_HTTP_PORT}
FAUCET_PORT=${FAUCET_PORT}
HEALTH_REFERENCE_RPC=${HEALTH_REFERENCE_RPC:-}
EOF
}

setup_health() {
  install -m 0755 "${HERE}/health.sh" /usr/local/lib/sova-infra/health.sh
  health_env_text >"${ETC}/host.env"
  chmod 0644 "${ETC}/host.env"
  install -m 0644 "${HERE}/systemd/sova-health.service" "${HERE}/systemd/sova-health.timer" "${UNIT_DIR}/"
  systemctl daemon-reload
  systemctl enable --now sova-health.timer >/dev/null 2>&1
}

# ---- no keys on public boxes (infra-m1 §4.1, M1 checklist) ------------------------------
check_no_keys() {
  case "${ROLE}" in
    seed | rpc)
      local found
      # -xdev per starting point: the root disk and the data volume.
      # sed -n 1,5p, not head -5: it reads to EOF, so find is never SIGPIPEd
      # into a silent set -e abort (pipefail) before the die below.
      found="$(find / "${DATA}" -xdev \( -name 'keystore*.json' -o -name 'miner.json' -o -name '*.keystore' \) \
        -not -path '/var/lib/docker/*' 2>/dev/null | sed -n 1,5p)"
      [[ -z "${found}" ]] || die "signing key material on a public ${ROLE} box: ${found}"
      [[ ! -d "${DATA}/faucet" && ! -d "${DATA}/keeper" && ! -d "${DATA}/sealer" ]] ||
        die "faucet/keeper/sealer state on a public ${ROLE} box"
      log "no-keys check passed (only the p2p node key and SSH host keys)"
      ;;
  esac
}

# --render: the files this host would get, written under $RENDER, using
# the same text functions as the real setup. Nothing is installed or run.
render_host() {
  install -d "${ETC}" "${UNIT_DIR}"
  write_zebrad_files "$(zebra_ref)"
  cp "${HERE}/systemd/zebrad.service" "${HERE}/systemd/sova-health.service" \
    "${HERE}/systemd/sova-health.timer" "${UNIT_DIR}/"
  health_env_text >"${ETC}/host.env"
  if has_node; then
    local mode_lines="SOVA_FOLLOW_ONLY=1" rpc_profile=public
    if [[ "${ROLE}" == keeper ]]; then
      # The real value comes from `sova-miner init` on the host.
      mode_lines="$(keeper_mode_lines "0x<keeper-evm-from-sova-miner-init>")"
      rpc_profile=local
    fi
    node_env_text "${mode_lines}" "${rpc_profile}" >"${ETC}/sova-node.env"
    cp "${HERE}/systemd/sova-node.service" "${UNIT_DIR}/"
    [[ -z "${SOVA_EPOCH_BASE}" ]] || echo "${SOVA_EPOCH_BASE}" >"${ETC}/epoch-base-pinned"
  fi
  if [[ "${ROLE}" == faucet ]]; then
    faucet_toml_text >"${ETC}/faucet.toml"
    cp "${HERE}/systemd/sova-faucet.service" "${UNIT_DIR}/"
  fi
  if [[ "${ROLE}" == keeper ]]; then
    keeper_env_text >"${ETC}/keeper.env"
    cp "${HERE}/systemd/sova-keeper.service" "${UNIT_DIR}/"
  fi
  has_tunnel && cp "${HERE}/systemd/cloudflared.service" "${UNIT_DIR}/"
  log "rendered into ${RENDER}"
}

if [[ -n "${RENDER}" ]]; then
  render_host
  exit 0
fi

mount_volume
setup_dirs
if [[ "${2:-}" == --enode-only ]]; then
  # deploy.sh's first pass: make (or read) the node key and print the
  # enode, so every node's bootnode list can be written before any starts.
  has_node && node_key_and_enode
  exit 0
fi
log "setting up ${ROLE} on $(hostname) (${PUBLIC_IPV4}), release ${SOVA_RELEASE_TAG}"
setup_ufw
setup_zebrad
install_binaries
[[ "${ROLE}" == keeper ]] && setup_keeper
has_node && setup_node
[[ "${ROLE}" == faucet ]] && setup_faucet
has_tunnel && setup_cloudflared
setup_health
check_no_keys
out release "${SOVA_RELEASE_TAG}"
log "done"
