#!/usr/bin/env bash
# infra/testnet/host/setup-host.sh -- configure one M1 testnet host for its
# role. Run as root by deploy.sh (never by hand on a laptop). Idempotent:
# re-running converges, and is how binaries are upgraded (new tag in
# host.env) and how the epoch base / bootnodes are rolled out.
#
#   setup-host.sh <host.env>               full setup
#   setup-host.sh <host.env> --enode-only  node key + enode only
#   setup-host.sh <host.env> --zebra-only  zebrad only (deploy.sh --zebra-only):
#                                          pull, write zebrad.env/.toml and the
#                                          health env, restart zebrad if they
#                                          changed (muted, then the readiness
#                                          wait); nothing else is touched or
#                                          restarted
#   setup-host.sh <host.env> --render DIR  write the files this host would
#                                          get (/etc/sova/*, units) under
#                                          DIR and stop: no root, no
#                                          network, runs on a laptop
#                                          (deploy.sh render uses it)
#
# host.env (generated by deploy.sh, nothing secret) sets ROLE and the
# config.env values below. Roles:
#   seed   zebrad (inbound 18233) + sova-node follow-only, P2P inbound
#   rpc    zebrad + sova-node follow-only (public RPC profile) + cloudflared
#   faucet zebrad + sova-faucet (own hot key) + cloudflared; with
#          CHECKOUT_RELAYER=1 also sova-checkout-relayer (the Ashwings ZEC
#          checkout's public relayer: Node, its own hot key, loopback only)
#   keeper zebrad + sova-node in MINE mode (seals, incl. null blocks;
#          with SOVA_SIP6=1 it signs as the keeper's miner key)
#          + sova-keeper burner (installed, not started)
# Every role: a SWAP_GB (default 4; 0 = none) /swapfile, vm.swappiness=10,
# and the health timer (host/health.sh).
#
# SOVA_SIP6=1 (the default): every node requires SIP-6 sealed or null
# blocks, and the keeper's node signs with a 0600 copy of the keeper's
# sova-miner keystore owned by the node's user (sova), at
# /var/lib/sova/sealer/keystore.json. Its seal journal lives under the
# persistent SOVA_DATADIR (/var/lib/sova/node/seal-journal/<address>).
#
# SOVA_SIP7=1 (the default): every node runs SIP-7 (Zcash pool state) and
# boots the genesis with the ZcashBlocks predeploy at 0x...5A01, a
# different genesis hash from SIP-7 off. Nodes with different values do
# not peer (fork ID), so every node renders the same one.
#
# Every zebrad restart (either mode) mutes this host's Telegram alerts for
# ZEBRA_RESTART_MUTE_MIN (15; host/maint.sh mute) and then waits until
# zebrad is ready again (host/zebra-ready.sh: RPC, image, NU7 height, state
# format upgrade, caught up), up to ZEBRA_READY_TIMEOUT_MIN (15; 0 = don't
# wait). Not ready: this script fails, and so does deploy.sh.
#
# The keeper pause (host/maint.sh keeper-pause, /etc/sova/.keeper-paused):
# while it is on, sova-node and sova-keeper are configured but never
# started or restarted here.
#
# Lines starting "KIT-OUT " are machine-read by deploy.sh (enode, faucet
# t-addr, keeper addresses, zebrad readiness timings: all public).
set -euo pipefail

ENV_FILE="${1:?usage: setup-host.sh <host.env>}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "${ENV_FILE}"

: "${ROLE:?}" "${PUBLIC_IPV4:?}" "${SOVA_RELEASE_TAG:?}" "${SOVA_RELEASE_REPO:?}"
: "${ZEBRA_IMAGE:?}" "${SOVA_P2P_PORT:?}" "${ZEBRA_P2P_PORT:?}" "${ZEBRA_RPC_PORT:?}"
: "${SOVA_HTTP_PORT:?}" "${SOVA_AUTH_PORT:?}" "${FAUCET_PORT:?}"
SOVA_EPOCH_BASE="${SOVA_EPOCH_BASE:-}"
SOVA_BOOTNODES="${SOVA_BOOTNODES:-}"
SOVA_EMISSION_SCHEDULE="${SOVA_EMISSION_SCHEDULE:-flat}"
SOVA_SIP6="${SOVA_SIP6:-1}"
SOVA_SIP7="${SOVA_SIP7:-1}"
BUILD_FROM_SOURCE="${BUILD_FROM_SOURCE:-0}"
CHECKOUT_RELAYER="${CHECKOUT_RELAYER:-0}"
SWAP_GB="${SWAP_GB:-4}"

DATA=/var/lib/sova
ETC=/etc/sova
# SIP-6: the keeper node's sealing key, a copy of the keeper's miner
# keystore readable only by the node's user (sova-node.service User=sova).
SEALER_KEYSTORE="${DATA}/sealer/keystore.json"
UNIT_DIR=/etc/systemd/system
SYSCTL_DIR=/etc/sysctl.d
RENDER=""
if [[ "${2:-}" == --render ]]; then
  RENDER="${3:?--render needs a directory}"
  ETC="${RENDER}/etc/sova"
  UNIT_DIR="${RENDER}/etc/systemd/system"
  SYSCTL_DIR="${RENDER}/etc/sysctl.d"
fi
# The keeper pause marker (host/maint.sh keeper-pause).
KEEPER_PAUSED_FILE="${ETC}/.keeper-paused"
PLATFORM=linux-x86_64
ASSET="sova-box-bin-${PLATFORM}.tar.gz"

log() { printf '[setup-host %s] %s\n' "${ROLE}" "$*"; }
die() {
  printf '[setup-host %s] error: %s\n' "${ROLE}" "$*" >&2
  exit 1
}
# To stderr, so it survives command substitution; deploy.sh reads 2>&1.
out() { printf 'KIT-OUT %s %s\n' "$1" "$2" >&2; }

if [[ -z "${RENDER}" ]]; then
  [[ "$(id -u)" == 0 ]] || die "run as root"
  [[ "$(uname -m)" == x86_64 ]] || die "x86_64 only (the release ships ${PLATFORM})"
  # shellcheck source=/dev/null
  . /etc/os-release
  [[ "${ID}" == ubuntu ]] || die "Ubuntu expected, got ${ID}"
fi
case "${ROLE}" in seed | rpc | faucet | keeper) ;; *) die "unknown ROLE ${ROLE}" ;; esac
[[ -z "${SOVA_EPOCH_BASE}" || "${SOVA_EPOCH_BASE}" =~ ^[1-9][0-9]*$ ]] || die "SOVA_EPOCH_BASE must be a positive integer"
case "${SOVA_EMISSION_SCHEDULE}" in sip3 | flat) ;; *) die "SOVA_EMISSION_SCHEDULE must be sip3 or flat" ;; esac
case "${SOVA_SIP6}" in 0 | 1) ;; *) die "SOVA_SIP6 must be 0 or 1" ;; esac
case "${SOVA_SIP7}" in 0 | 1) ;; *) die "SOVA_SIP7 must be 0 or 1" ;; esac
case "${CHECKOUT_RELAYER}" in 0 | 1) ;; *) die "CHECKOUT_RELAYER must be 0 or 1" ;; esac
if ! [[ "${SWAP_GB}" =~ ^[0-9]+$ ]] || ((SWAP_GB > 64)); then die "SWAP_GB must be 0..64 (GB; 0 = no swapfile)"; fi

has_node() { [[ "${ROLE}" == seed || "${ROLE}" == rpc || "${ROLE}" == keeper ]]; }
has_tunnel() { [[ "${ROLE}" == rpc || "${ROLE}" == faucet ]]; }
has_relayer() { [[ "${ROLE}" == faucet && "${CHECKOUT_RELAYER}" == 1 ]]; }
keeper_paused() { [[ "${ROLE}" == keeper && -f "${KEEPER_PAUSED_FILE}" ]]; }
paused_since() { sed -n 's/^since=//p' "${KEEPER_PAUSED_FILE}" 2>/dev/null; }
if has_relayer; then
  : "${CHECKOUT_RELAYER_PORT:?}" "${CHECKOUT_RELAYER_SOVA_RPC:?}" "${CHECKOUT_RELAYER_CORS_ORIGIN:?}" "${CHECKOUT_RELAYER_NODE_MAJOR:?}"
fi

# ---- data volume ----------------------------------------------------------------
mount_volume() {
  local devs=() d uuid
  for d in /dev/disk/by-id/scsi-0HC_Volume_*; do [[ -e "${d}" ]] && devs+=("${d}"); done
  mkdir -p "${DATA}"
  if [[ ${#devs[@]} -eq 0 ]]; then
    # Also the normal case on an (optional) byo host, e.g. an AWS keeper
    # with one 40 GB gp3 root volume.
    log "no Hetzner volume attached; state lives on the root disk"
    return 0
  fi
  [[ ${#devs[@]} -eq 1 ]] || die "expected one attached volume, found ${#devs[@]}"
  uuid="$(blkid -s UUID -o value "${devs[0]}")" || die "volume ${devs[0]} has no filesystem (provision.sh formats it ext4)"
  if ! grep -q "UUID=${uuid}" /etc/fstab; then
    echo "UUID=${uuid} ${DATA} ext4 defaults,discard,nofail 0 2" >>/etc/fstab
  fi
  mountpoint -q "${DATA}" || mount "${DATA}"
  log "data volume ${devs[0]} mounted at ${DATA}"
}

# ---- swap ---------------------------------------------------------------------------------
# A SWAP_GB swapfile on every host (0 = the kit manages none), and
# vm.swappiness=10 so the kernel drops page cache before it swaps out the
# nodes' working sets: swap is a cushion against running out of memory, not
# extra RAM. 2026-09-27: reth's state cache filled the 4 GB hosts, which had
# no swap; zebrad stopped answering, the chain stalled ~20 min and the
# public RPC host thrashed. An active /swapfile (e.g. one made by hand) is
# left as it is, whatever its size.
SWAPFILE=/swapfile
SWAP_SYSCTL_FILE=60-sova-swap.conf

swap_sysctl_text() {
  cat <<EOF
# Written by setup-host.sh; re-run deploy.sh to change it. Drop page cache
# before swapping out the nodes' working sets (swap is a cushion).
vm.swappiness=10
EOF
}

swap_fstab_line() { printf '%s none swap sw 0 0\n' "${SWAPFILE}"; }

# The swap line for the render log: what setup_swap would do.
swap_plan() {
  if [[ "${SWAP_GB}" == 0 ]]; then
    echo "swap: SWAP_GB=0, no swapfile managed; vm.swappiness=10"
  else
    echo "swap: ${SWAPFILE} ${SWAP_GB} GB if absent (fallocate, chmod 600, mkswap, swapon; fstab '$(swap_fstab_line)'); vm.swappiness=10"
  fi
}

# Whether $SWAPFILE is an active swap area now.
swapfile_active() {
  local active
  active="$(swapon --show=NAME --noheadings 2>/dev/null || true)"
  grep -qxF "${SWAPFILE}" <<<"${active}"
}

setup_swap() {
  local f="${SWAPFILE}" conf="${SYSCTL_DIR}/${SWAP_SYSCTL_FILE}"
  # swappiness always: harmless without swap, and useful with a host's own.
  install -d -m 0755 "${SYSCTL_DIR}"
  swap_sysctl_text >"${conf}.new"
  if cmp -s "${conf}.new" "${conf}"; then
    rm -f "${conf}.new"
  else
    mv "${conf}.new" "${conf}"
    chmod 0644 "${conf}"
    log "sysctl: vm.swappiness=10 (${conf})"
  fi
  sysctl -q -p "${conf}" >/dev/null || log "WARNING: sysctl could not load ${conf} (vm.swappiness is $(cat /proc/sys/vm/swappiness 2>/dev/null))"
  if [[ "${SWAP_GB}" == 0 ]]; then
    log "swap: SWAP_GB=0, no swapfile managed (swap now: $(free -m | awk '/^Swap:/ { print $2 " MB" }'))"
    return 0
  fi
  if swapfile_active; then
    log "swap: ${f} already active ($(swapon --show=NAME,SIZE --noheadings | awk -v f="${f}" '$1 == f { print $2 }')), left as is"
  else
    if [[ -e "${f}" ]]; then
      chmod 0600 "${f}"
      if swapon "${f}" 2>/dev/null; then
        log "swap: ${f} existed but was off: turned it on"
      else
        # Not a swap area (e.g. a create that died before mkswap): redo it.
        rm -f "${f}"
        log "swap: ${f} existed but was not a usable swap area: re-creating it"
      fi
    fi
    if ! swapfile_active; then
      local avail_mb need_mb=$((SWAP_GB * 1024 + 2048))
      avail_mb="$(df --output=avail -m / | tail -1 | tr -dc '0-9')"
      if [[ -z "${avail_mb}" ]] || ((avail_mb < need_mb)); then
        log "WARNING: swap: only ${avail_mb:-?} MB free on /, need ${need_mb} (SWAP_GB=${SWAP_GB} + 2 GB): NO swapfile made; lower SWAP_GB or free the disk"
        return 0
      fi
      if ! { fallocate -l "${SWAP_GB}G" "${f}" 2>/dev/null ||
        dd if=/dev/zero of="${f}" bs=1M count=$((SWAP_GB * 1024)) status=none; }; then
        rm -f "${f}"
        die "swap: could not allocate ${f} (${SWAP_GB} GB)"
      fi
      chmod 0600 "${f}"
      mkswap "${f}" >/dev/null || { rm -f "${f}"; die "swap: mkswap ${f} failed"; }
      swapon "${f}" || die "swap: swapon ${f} failed"
      log "swap: created ${f} (${SWAP_GB} GB) and turned it on"
    fi
  fi
  if grep -qE "^[[:space:]]*${f}[[:space:]]" /etc/fstab; then
    log "swap: ${f} already in /etc/fstab"
  else
    swap_fstab_line >>/etc/fstab
    log "swap: added '$(swap_fstab_line)' to /etc/fstab"
  fi
}

# ---- users and directories --------------------------------------------------------
ensure_user() { # name [uid]
  if ! id -u "$1" >/dev/null 2>&1; then
    if [[ -n "${2:-}" ]]; then
      groupadd --system --gid "$2" "$1"
      useradd --system --uid "$2" --gid "$2" --home-dir /nonexistent --shell /usr/sbin/nologin "$1"
    else
      useradd --system --user-group --home-dir /nonexistent --shell /usr/sbin/nologin "$1"
    fi
  fi
}

setup_dirs() {
  # The zfnd/zebra image runs zebrad as uid/gid 10001.
  ensure_user zebra 10001
  install -d -m 0750 -o 10001 -g 10001 "${DATA}/zebrad"
  install -d -m 0755 "${ETC}" /usr/local/lib/sova-infra
  if has_node; then
    ensure_user sova
    install -d -m 0700 -o sova -g sova "${DATA}/node" "${DATA}/node/tmp"
  fi
  if [[ "${ROLE}" == faucet ]]; then
    ensure_user sova-faucet
    install -d -m 0700 -o sova-faucet -g sova-faucet "${DATA}/faucet"
  fi
  if has_relayer; then
    ensure_user sova-checkout
    install -d -m 0700 -o sova-checkout -g sova-checkout "${DATA}/checkout-relayer"
  fi
  if [[ "${ROLE}" == keeper ]]; then
    ensure_user sova-keeper
    install -d -m 0700 -o sova-keeper -g sova-keeper "${DATA}/keeper"
  fi
}

# ---- host firewall (mirrors the Hetzner firewall / a byo host's security group;
# defence in depth) -----------------------------------------------------------------
setup_ufw() {
  ufw default deny incoming >/dev/null
  ufw default allow outgoing >/dev/null
  ufw allow 22/tcp >/dev/null
  if [[ "${ROLE}" == seed ]]; then
    ufw allow "${SOVA_P2P_PORT}/tcp" >/dev/null
    ufw allow "${SOVA_P2P_PORT}/udp" >/dev/null
    ufw allow "${ZEBRA_P2P_PORT}/tcp" >/dev/null
  fi
  ufw --force enable >/dev/null
  log "ufw: $(ufw status | grep -c ALLOW) allow rule(s)"
}

# ---- zebrad -------------------------------------------------------------------------
zebra_ref() {
  local ref="${ZEBRA_IMAGE}"
  [[ -n "${ZEBRA_IMAGE_DIGEST:-}" ]] && ref="${ZEBRA_IMAGE}@${ZEBRA_IMAGE_DIGEST}"
  printf '%s' "${ref}"
}

write_zebrad_files() { # image-ref
  printf 'ZEBRA_IMAGE_REF=%s\n' "$1" >"${ETC}/zebrad.env"
  sed -e "s/@ZEBRA_P2P_PORT@/${ZEBRA_P2P_PORT}/" -e "s/@ZEBRA_RPC_PORT@/${ZEBRA_RPC_PORT}/" \
    "${HERE}/zebrad.toml" >"${ETC}/zebrad.toml"
  chmod 0644 "${ETC}/zebrad.toml"
}

setup_zebrad() {
  local ref
  ref="$(zebra_ref)"
  docker pull -q "${ref}" >/dev/null || die "docker pull ${ref} failed"
  write_zebrad_files "${ref}"
  install -m 0644 "${HERE}/systemd/zebrad.service" "${UNIT_DIR}/zebrad.service"
  systemctl daemon-reload
  systemctl enable zebrad >/dev/null 2>&1
  # Restart only if the image or config changed (a restart costs a
  # RocksDB reopen, not a resync).
  local sum
  sum="$(cat "${ETC}/zebrad.env" "${ETC}/zebrad.toml" | sha256sum | cut -d' ' -f1)"
  if [[ "$(cat "${ETC}/.zebrad.sum" 2>/dev/null)" != "${sum}" ]] || ! systemctl is-active --quiet zebrad; then
    # Where zebrad is before the restart ("<tip> <lag behind the
    # references>", "- 0" when it doesn't answer), for the readiness wait.
    local pre t0 t1 mute="${ZEBRA_RESTART_MUTE_MIN:-15}"
    pre="$(ZEBRA_READY_ENV="${ENV_FILE}" bash "${HERE}/zebra-ready.sh" before)" || pre="- 0"
    # Planned noise (zebrad_down, a short epoch_lag): no Telegram for a while.
    [[ "${mute}" == 0 ]] || bash "${HERE}/maint.sh" mute "${mute}" "zebrad restart (${ref##*/})"
    t0="$(date +%s)"
    systemctl restart zebrad
    t1="$(date +%s)"
    echo "${sum}" >"${ETC}/.zebrad.sum"
    log "zebrad (re)started with ${ref}"
    ZEBRA_READY_ENV="${ENV_FILE}" bash "${HERE}/zebra-ready.sh" wait --since "${t0}" --started "${t1}" \
      --pre-tip "${pre% *}" --pre-lag "${pre#* }" ||
      die "zebrad is not ready after the restart (above); the rollout stops here"
  else
    log "zebrad unchanged and running"
  fi
}

# ---- binaries: tagged GitHub Release, SHA256SUMS verified -------------------------
# Same checks as box/up.sh's fetch_prebuilt_from_release/verify_prebuilt:
# release-level SHA256SUMS over the tarball, release BUILD-INFO names the
# tag and platform, the tarball's own SHA256SUMS over both binaries, and
# the tarball's BUILD-INFO commit equals the release's.
RELEASE_COMMIT=""
install_release_binaries() {
  local dest="/usr/local/lib/sova/${SOVA_RELEASE_TAG}"
  if [[ -x "${dest}/sova" && -x "${dest}/sova-miner" && -s "${dest}/COMMIT" ]]; then
    RELEASE_COMMIT="$(cat "${dest}/COMMIT")"
    log "release ${SOVA_RELEASE_TAG} already installed (${RELEASE_COMMIT:0:12})"
    return 0
  fi
  local tmp base expected actual rel_tag rel_platforms inner_commit inner_platform f
  tmp="$(mktemp -d)"
  base="https://github.com/${SOVA_RELEASE_REPO}/releases/download/${SOVA_RELEASE_TAG}"
  for f in SHA256SUMS BUILD-INFO "${ASSET}"; do
    curl -fsSL --retry 3 -o "${tmp}/${f}" "${base}/${f}" || {
      rm -rf "${tmp}"
      return 1
    }
  done
  expected="$(awk -v n="${ASSET}" '$2 == n || $2 == ("*" n) { print $1; exit }' "${tmp}/SHA256SUMS")"
  actual="$(sha256sum "${tmp}/${ASSET}" | cut -d' ' -f1)"
  [[ -n "${expected}" && "${expected}" == "${actual}" ]] || die "release ${ASSET}: SHA-256 mismatch (SHA256SUMS '${expected:0:12}', got '${actual:0:12}')"
  rel_tag="$(sed -n 's/^tag=//p' "${tmp}/BUILD-INFO")"
  rel_platforms="$(sed -n 's/^platforms=//p' "${tmp}/BUILD-INFO")"
  RELEASE_COMMIT="$(sed -n 's/^commit=//p' "${tmp}/BUILD-INFO")"
  [[ "${rel_tag}" == "${SOVA_RELEASE_TAG}" ]] || die "release BUILD-INFO names tag '${rel_tag}', expected ${SOVA_RELEASE_TAG}"
  [[ " ${rel_platforms} " == *" ${PLATFORM} "* ]] || die "release does not list ${PLATFORM}"
  mkdir -p "${tmp}/x"
  tar -xzf "${tmp}/${ASSET}" -C "${tmp}/x" sova sova-miner SHA256SUMS BUILD-INFO ||
    die "${ASSET} does not unpack to sova, sova-miner, SHA256SUMS, BUILD-INFO"
  # Only the two binaries installed here: from v0.1.20 the tarball's
  # SHA256SUMS also lists sova-rebuild and sova-near-da, not unpacked here.
  if ! grep -Eq '^[0-9a-f]{64}  sova$' "${tmp}/x/SHA256SUMS" ||
    ! grep -Eq '^[0-9a-f]{64}  sova-miner$' "${tmp}/x/SHA256SUMS"; then
    die "tarball SHA256SUMS does not cover sova and sova-miner"
  fi
  (cd "${tmp}/x" && grep -E '^[0-9a-f]{64}  (sova|sova-miner)$' SHA256SUMS | sha256sum -c --quiet -) ||
    die "tarball SHA256SUMS check failed"
  inner_commit="$(sed -n 's/^commit=//p' "${tmp}/x/BUILD-INFO")"
  inner_platform="$(sed -n 's/^platform=//p' "${tmp}/x/BUILD-INFO")"
  [[ "${inner_commit}" == "${RELEASE_COMMIT}" ]] || die "tarball commit ${inner_commit} != release commit ${RELEASE_COMMIT}"
  [[ "${inner_platform}" == "${PLATFORM}" ]] || die "tarball is for ${inner_platform}"
  install -d "${dest}"
  install -m 0755 "${tmp}/x/sova" "${tmp}/x/sova-miner" "${dest}/"
  install -m 0644 "${tmp}/x/SHA256SUMS" "${tmp}/x/BUILD-INFO" "${dest}/"
  echo "${RELEASE_COMMIT}" >"${dest}/COMMIT"
  rm -rf "${tmp}"
  log "installed release ${SOVA_RELEASE_TAG} (${RELEASE_COMMIT:0:12}), SHA256SUMS verified"
}

# Source build (the faucet always; everything with BUILD_FROM_SOURCE=1).
# Checks the tag's commit against the release's when there is one.
SRC=""
ensure_source() {
  [[ -n "${SRC}" ]] && return 0
  apt-get update -qq && apt-get install -y -qq build-essential pkg-config clang >/dev/null
  ensure_user sova-build
  install -d -m 0755 -o sova-build -g sova-build "${DATA}/build"
  local home="${DATA}/build"
  if [[ ! -x "${home}/.cargo/bin/cargo" ]]; then
    sudo -u sova-build HOME="${home}" sh -c \
      'curl -fsSL https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable' >/dev/null
  fi
  SRC="${home}/src-${SOVA_RELEASE_TAG}"
  if [[ ! -d "${SRC}/.git" ]]; then
    sudo -u sova-build git clone -q --depth 1 --branch "${SOVA_RELEASE_TAG}" "${SOVA_SOURCE_REPO_URL}" "${SRC}"
  fi
  local head
  head="$(sudo -u sova-build git -C "${SRC}" rev-parse HEAD)"
  if [[ -n "${RELEASE_COMMIT}" && "${head}" != "${RELEASE_COMMIT}" ]]; then
    die "tag ${SOVA_RELEASE_TAG} is ${head} in ${SOVA_SOURCE_REPO_URL}, but the release was built from ${RELEASE_COMMIT}"
  fi
  log "source ${SOVA_RELEASE_TAG} at ${head:0:12}"
}

cargo_build() { # cargo args...
  sudo -u sova-build HOME="${DATA}/build" CARGO_TARGET_DIR="${DATA}/build/target" \
    sh -c 'cd "$0" && "$HOME/.cargo/bin/cargo" build --release --locked "$@"' "${SRC}" "$@"
}

install_binaries() {
  local dest="/usr/local/lib/sova/${SOVA_RELEASE_TAG}"
  if [[ "${BUILD_FROM_SOURCE}" == 1 ]] || ! install_release_binaries; then
    [[ "${BUILD_FROM_SOURCE}" == 1 ]] || log "release download failed; building from source (slow: reth, ~20-40 min)"
    ensure_source
    cargo_build -p sova
    cargo_build -p sova-miner --manifest-path crates/burn-wallet/Cargo.toml
    install -d "${dest}"
    install -m 0755 "${DATA}/build/target/release/sova" "${DATA}/build/target/release/sova-miner" "${dest}/"
    # shellcheck disable=SC2024 # root writes the file; git runs as the build user
    sudo -u sova-build git -C "${SRC}" rev-parse HEAD >"${dest}/COMMIT"
  fi
  if [[ "${ROLE}" == faucet && ! -x "${dest}/sova-faucet" ]]; then
    # Not in the release tarball; the burn-wallet workspace doesn't link
    # reth, so this is a few minutes.
    ensure_source
    cargo_build -p sova-faucet --manifest-path crates/burn-wallet/Cargo.toml
    install -m 0755 "${DATA}/build/target/release/sova-faucet" "${dest}/"
  fi
  local b
  for b in sova sova-miner sova-faucet; do
    [[ -x "${dest}/${b}" ]] && ln -sfn "${dest}/${b}" "/usr/local/bin/${b}"
  done
  echo "${SOVA_RELEASE_TAG}" >"${ETC}/release"
}

# ---- sova node ----------------------------------------------------------------------
node_key_and_enode() {
  local key="${DATA}/node/discovery-secret"
  if [[ ! -s "${key}" ]]; then
    # Pre-generated so the enode is known before the first start, and
    # stable across restarts (SOVA_DATADIR). reth parses exactly 64 hex
    # chars: no trailing newline.
    (umask 077 && openssl rand -hex 32 | tr -d '\n' >"${key}")
    chown sova:sova "${key}"
  fi
  chmod 0600 "${key}"
  local enode
  enode="$(python3 "${HERE}/enode.py" "${key}" "${PUBLIC_IPV4}" "${SOVA_P2P_PORT}")"
  echo "${enode}" >"${ETC}/enode"
  out enode "${enode}"
}

# No SOVA_RPC_CORS here on purpose: every host's RPC binds 127.0.0.1, and
# the only browser-facing path is rpc.<domain> through the edge Worker
# (worker/rpc-firewall.mjs), which answers CORS itself.
# SOVA_SYNC_STALL_EXIT_SECS: a catch-up whose head stays frozen while every
# forkchoice answers Syncing for 10 min exits the node, and systemd
# (Restart=always) brings it back with reth's pinned backfill target gone
# (engine::candidates::SYNC_STALL_EXIT_ENV; 2026-10-01 seed-1 stall).
node_env_text() { # mode-lines rpc-profile
  cat <<EOF
# Written by setup-host.sh (${ROLE}); re-run deploy.sh to change it.
SOVA_CHAIN=sova-testnet
SOVA_GOSSIP=p2p
$1
SOVA_ZEBRAD_RPC=http://127.0.0.1:${ZEBRA_RPC_PORT}
SOVA_EPOCH_BASE=${SOVA_EPOCH_BASE}
SOVA_EMISSION_SCHEDULE=${SOVA_EMISSION_SCHEDULE}
SOVA_SIP6=${SOVA_SIP6}
SOVA_SIP7=${SOVA_SIP7}
SOVA_DATADIR=${DATA}/node
SOVA_BOOTNODES=${SOVA_BOOTNODES}
SOVA_P2P_PEERS=$([[ "${ROLE}" == seed ]] || printf '%s' "${SOVA_BOOTNODES}")
SOVA_P2P_PORT=${SOVA_P2P_PORT}
SOVA_NAT=extip:${PUBLIC_IPV4}
SOVA_HTTP_PORT=${SOVA_HTTP_PORT}
SOVA_AUTH_PORT=${SOVA_AUTH_PORT}
SOVA_RPC_PROFILE=$2
SOVA_SYNC_STALL_EXIT_SECS=600
RUST_LOG=info
RUST_LOG_STYLE=never
NO_COLOR=1
EOF
}

# The genesis hash this host's node boots, from the installed binary itself
# (`sova genesis-hash`: the chainspec for SOVA_CHAIN and SOVA_SIP7, with
# SIP-7's ZcashBlocks predeploy; nothing is started). deploy.sh records it
# as out/servers/<name>.genesis_hash and bootnodes.sh publishes it, so the
# hash is never hard-coded in the kit. A release older than the subcommand
# would ignore the argument and start a node, so it is only run when the
# binary carries the subcommand's usage text; env -i keeps every other
# SOVA_* setting away from it.
node_genesis_hash() {
  local bin=/usr/local/bin/sova hash
  if ! grep -aq 'sova genesis-hash' "${bin}"; then
    log "WARNING: sova ${SOVA_RELEASE_TAG} has no 'genesis-hash' subcommand: genesis hash not recorded (bootnodes.sh refuses to publish without it)"
    return 0
  fi
  hash="$(timeout 60 env -i SOVA_CHAIN=sova-testnet SOVA_SIP7="${SOVA_SIP7}" "${bin}" genesis-hash)" ||
    die "sova genesis-hash failed"
  [[ "${hash}" =~ ^0x[0-9a-f]{64}$ ]] || die "sova genesis-hash printed '${hash}', not a hash"
  log "genesis hash (SIP-7 $([[ "${SOVA_SIP7}" == 1 ]] && echo on || echo off)): ${hash}"
  out genesis_hash "${hash}"
  out genesis_sip7 "${SOVA_SIP7}"
}

setup_node() {
  node_key_and_enode

  local mode_lines rpc_profile=public
  if [[ "${ROLE}" == keeper ]]; then
    # Mine mode: seals its own burns' epochs, and null blocks (SIP-6
    # §2.4; rewardless cadence blocks with SIP-6 off) for burn-less
    # epochs, so the chain has a producer on day 1. It is an ordinary
    # sealer with no privilege (D8). With SIP-6 it signs as the keeper's
    # miner key and journals under SOVA_DATADIR (persistent).
    local evm
    evm="$(keeper_evm_address)"
    mode_lines="$(keeper_mode_lines "${evm}")"
    rpc_profile=local
  else
    mode_lines="SOVA_FOLLOW_ONLY=1"
  fi
  local changed=0
  if [[ "${ROLE}" == keeper && "${SOVA_SIP6}" == 1 ]]; then
    install_sealer_key
    [[ ${SEALER_KEY_CHANGED} == 0 ]] || changed=1
  fi
  node_env_text "${mode_lines}" "${rpc_profile}" >"${ETC}/sova-node.env.new"
  if ! cmp -s "${ETC}/sova-node.env.new" "${ETC}/sova-node.env"; then
    mv "${ETC}/sova-node.env.new" "${ETC}/sova-node.env"
    changed=1
  else
    rm -f "${ETC}/sova-node.env.new"
  fi
  chmod 0644 "${ETC}/sova-node.env"
  node_genesis_hash
  install -m 0644 "${HERE}/systemd/sova-node.service" "${UNIT_DIR}/sova-node.service"
  systemctl daemon-reload
  systemctl enable sova-node >/dev/null 2>&1
  if [[ -z "${SOVA_EPOCH_BASE}" ]]; then
    rm -f "${ETC}/epoch-base-pinned"
    systemctl stop sova-node 2>/dev/null || true
    log "sova-node installed, NOT started: SOVA_EPOCH_BASE is not pinned yet (runbook: Pin B)"
    return 0
  fi
  echo "${SOVA_EPOCH_BASE}" >"${ETC}/epoch-base-pinned"
  # Peer ban length (reth.toml [peers] ban_duration, reth default 12 h): one
  # failed handshake bans the remote IP, so behind a shared VPN exit or
  # carrier NAT one misconfigured node locks everyone there out of the seeds.
  # 1 h (Rob, 2026-09-26). reth writes reth.toml on its first start, so a new
  # host picks this up on its second deploy.
  local toml="${DATA}/node/reth.toml" ban="${PEER_BAN_DURATION:-1h}"
  if [[ -f "${toml}" ]] && ! grep -q "^ban_duration = \"${ban}\"$" "${toml}"; then
    sed -i "s/^ban_duration = \".*\"$/ban_duration = \"${ban}\"/" "${toml}"
    changed=1
    log "reth.toml: peer ban_duration ${ban}"
  fi
  if keeper_paused; then
    # Configured above; started by keeper-resume (with this config).
    log "sova-node NOT started or restarted: the keeper is paused (since $(paused_since), ${KEEPER_PAUSED_FILE}); ./deploy.sh keeper-resume starts it"
    return 0
  fi
  local bin_changed=0
  [[ "$(readlink /usr/local/bin/sova)" != "$(cat "${ETC}/.sova-node.bin" 2>/dev/null)" ]] && bin_changed=1
  if [[ ${changed} == 1 || ${bin_changed} == 1 ]] || ! systemctl is-active --quiet sova-node; then
    systemctl restart sova-node
    readlink /usr/local/bin/sova >"${ETC}/.sova-node.bin"
    log "sova-node (re)started (epoch base ${SOVA_EPOCH_BASE}, ${SOVA_EMISSION_SCHEDULE}, SIP-6 $([[ "${SOVA_SIP6}" == 1 ]] && echo on || echo off), SIP-7 $([[ "${SOVA_SIP7}" == 1 ]] && echo on || echo off))"
  else
    log "sova-node unchanged and running"
  fi
}

# ---- faucet ----------------------------------------------------------------------------
faucet_toml_text() {
  cat <<EOF
# Written by setup-host.sh. Defaults from
# crates/burn-wallet/faucet/faucet.example.toml; docs/ops/faucet.md.
network = "test"
listen = "127.0.0.1:${FAUCET_PORT}"
zebrad_rpc = "http://127.0.0.1:${ZEBRA_RPC_PORT}"
keystore = "${DATA}/faucet/keystore.json"
state_file = "${DATA}/faucet/state.json"
drip_zat = 10000000
address_cooldown_secs = 86400
ip_cooldown_secs = 86400
daily_cap_zat = 200000000
max_balance_multiple = 5
# cloudflared on this host is the only socket peer; believe its header.
trusted_proxy_header = "CF-Connecting-IP"
trusted_proxy_peers = ["127.0.0.1", "::1"]
status_cache_secs = 10
EOF
}

setup_faucet() {
  faucet_toml_text >"${ETC}/faucet.toml"
  chmod 0644 "${ETC}/faucet.toml"
  if [[ ! -s "${DATA}/faucet/keystore.json" ]]; then
    # The one hot key (D5). Created here, never copied anywhere; a rebuild
    # makes a new one (rotate = init again + fund the new address).
    sudo -u sova-faucet /usr/local/bin/sova-faucet init --keystore "${DATA}/faucet/keystore.json" --network test >/dev/null
  fi
  out faucet_taddr "$(sudo -u sova-faucet /usr/local/bin/sova-faucet address --config "${ETC}/faucet.toml")"
  install -m 0644 "${HERE}/systemd/sova-faucet.service" "${UNIT_DIR}/sova-faucet.service"
  systemctl daemon-reload
  systemctl enable sova-faucet >/dev/null 2>&1
  systemctl restart sova-faucet
  log "faucet running on 127.0.0.1:${FAUCET_PORT} (fund the t-addr with a plain transfer)"
}

# ---- checkout relayer (tools/checkout-relayer) --------------------------------------------
# The Ashwings ZEC checkout's public relayer. Code: deploy.sh copies this
# checkout's tools/checkout-relayer (src + lockfile) next to this script;
# npm ci (lockfile integrity hashes, no install scripts) runs as the build
# user, and the result is installed root-owned in /opt. It runs as
# sova-checkout, which can write only its state dir. Its hot key is made
# here (keygen.mjs) into a root 0600 env file that systemd reads before
# dropping privileges; like the faucet's key it is never copied anywhere,
# and deploy.sh records only the address (KIT-OUT checkout_relayer_address).
RELAYER_APP=/opt/sova-checkout-relayer
RELAYER_KEY_FILE="${ETC}/checkout-relayer.key.env"

checkout_relayer_env_text() {
  cat <<EOF
# Written by setup-host.sh (faucet); re-run deploy.sh to change it. Not
# secret: RELAYER_KEY is in checkout-relayer.key.env (root 0600, made on
# this host). Meanings: tools/checkout-relayer/README.md.
ASHWINGS=${CHECKOUT_ASHWINGS:-}
CHECKOUT=${CHECKOUT_RELAYER_CHECKOUT:-}
START_BLOCK=${CHECKOUT_START_BLOCK:-0}
LISTINGS=${CHECKOUT_RELAYER_LISTINGS:-1}
SOVA_RPC_URL=${CHECKOUT_RELAYER_SOVA_RPC}
RPC_PER_10S=${CHECKOUT_RELAYER_RPC_PER_10S:-30}
HOST=127.0.0.1
PORT=${CHECKOUT_RELAYER_PORT}
CORS_ORIGIN=${CHECKOUT_RELAYER_CORS_ORIGIN}
# cloudflared on this host is the only socket peer; believe its header.
TRUST_PROXY_HEADER=cf-connecting-ip
MAX_OPEN_RESERVATIONS=${CHECKOUT_RELAYER_MAX_OPEN:-20}
RESERVE_PER_IP_PER_HOUR=${CHECKOUT_RELAYER_RESERVE_PER_IP_PER_HOUR:-3}
RESERVE_PER_HOUR=${CHECKOUT_RELAYER_RESERVE_PER_HOUR:-60}
RESERVE_PER_MINUTE=${CHECKOUT_RELAYER_RESERVE_PER_MINUTE:-10}
CLAIM_PER_IP_PER_HOUR=${CHECKOUT_RELAYER_CLAIM_PER_IP_PER_HOUR:-20}
MIN_BALANCE_WEI=${CHECKOUT_RELAYER_MIN_BALANCE_WEI:-100000000000000000}
STATE_FILE=${DATA}/checkout-relayer/state.json
# The testnet SOVA drip (POST /drip): one Ashwings mint plus gas per new
# address, from this key; the relayer refuses it on any chain but 82330.
DRIP=${CHECKOUT_RELAYER_DRIP:-0}
DRIP_CHAIN_IDS=82330
DRIP_PER_IP_PER_DAY=${CHECKOUT_RELAYER_DRIP_PER_IP_PER_DAY:-2}
DRIP_PER_HOUR=${CHECKOUT_RELAYER_DRIP_PER_HOUR:-20}
DRIP_PER_DAY=${CHECKOUT_RELAYER_DRIP_PER_DAY:-100}
DRIP_KEEP_WEI=${CHECKOUT_RELAYER_DRIP_KEEP_WEI:-1000000000000000000}
# The payment watcher: this host's zebrad, read-only calls only.
ZCASH_RPC_URL=http://127.0.0.1:${ZEBRA_RPC_PORT}
ZCASH_NET=test
NODE_ENV=production
EOF
}

# Node LTS from NodeSource's signed apt repo (the cloudflared pattern);
# Ubuntu 24.04's own nodejs is 18.x. Pinned to CHECKOUT_RELAYER_NODE_MAJOR,
# preferred over Ubuntu's by an apt pin.
install_node() {
  local major="${CHECKOUT_RELAYER_NODE_MAJOR}" have=""
  command -v node >/dev/null 2>&1 && have="$(node --version)"
  if [[ "${have}" != "v${major}."* ]]; then
    install -d -m 0755 /usr/share/keyrings
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key |
      gpg --dearmor --yes -o /usr/share/keyrings/nodesource.gpg
    echo "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${major}.x nodistro main" \
      >/etc/apt/sources.list.d/nodesource.list
    printf 'Package: nodejs\nPin: origin deb.nodesource.com\nPin-Priority: 600\n' >/etc/apt/preferences.d/nodesource
    apt-get update -qq && apt-get install -y -qq nodejs >/dev/null
  fi
  have="$(node --version)"
  [[ "${have}" == "v${major}."* ]] || die "node ${have} installed, expected v${major}.x (NodeSource)"
  log "node ${have}"
}

# Installs the code if it (or node) changed. Sets RELAYER_CODE_CHANGED.
RELAYER_CODE_CHANGED=0
install_relayer_code() {
  local src="${HERE}/checkout-relayer" stage="${DATA}/build/checkout-relayer" sum
  [[ -f "${src}/package-lock.json" && -f "${src}/src/server.mjs" ]] ||
    die "no relayer code at ${src} (deploy.sh copies tools/checkout-relayer there)"
  sum="$( (cd "${src}" && find src package.json package-lock.json -type f | LC_ALL=C sort | xargs sha256sum && node --version) |
    sha256sum | cut -d' ' -f1)"
  if [[ "$(cat "${RELAYER_APP}/.sum" 2>/dev/null)" == "${sum}" ]]; then
    log "checkout relayer code unchanged"
    return 0
  fi
  ensure_user sova-build
  install -d -m 0755 -o sova-build -g sova-build "${DATA}/build"
  rm -rf "${stage}"
  install -d -m 0755 -o sova-build -g sova-build "${stage}"
  cp -R "${src}/src" "${src}/package.json" "${src}/package-lock.json" "${stage}/"
  chown -R sova-build:sova-build "${stage}"
  sudo -u sova-build HOME="${DATA}/build" sh -c 'cd "$0" && npm ci --omit=dev --ignore-scripts --no-audit --no-fund --loglevel=error' \
    "${stage}" >/dev/null || die "npm ci for the checkout relayer failed"
  install -d -m 0755 "${RELAYER_APP}"
  rsync -a --delete --chown=root:root --chmod=D755,F644 "${stage}/" "${RELAYER_APP}/"
  echo "${sum}" >"${RELAYER_APP}/.sum"
  RELAYER_CODE_CHANGED=1
  log "checkout relayer code installed in ${RELAYER_APP}"
}

setup_checkout_relayer() {
  install_node
  install_relayer_code
  local addr key_new=0
  [[ -s "${RELAYER_KEY_FILE}" ]] || key_new=1
  addr="$(umask 077 && node "${RELAYER_APP}/src/keygen.mjs" "${RELAYER_KEY_FILE}")" || die "checkout relayer keygen failed"
  chown root:root "${RELAYER_KEY_FILE}"
  chmod 0600 "${RELAYER_KEY_FILE}"
  [[ "${addr}" =~ ^0x[0-9a-fA-F]{40}$ ]] || die "keygen printed '${addr}', not an address"
  out checkout_relayer_address "${addr}"
  checkout_relayer_env_text >"${ETC}/checkout-relayer.env.new"
  local changed=${RELAYER_CODE_CHANGED}
  ((key_new == 0)) || changed=1
  if ! cmp -s "${ETC}/checkout-relayer.env.new" "${ETC}/checkout-relayer.env"; then
    mv "${ETC}/checkout-relayer.env.new" "${ETC}/checkout-relayer.env"
    changed=1
  else
    rm -f "${ETC}/checkout-relayer.env.new"
  fi
  chmod 0644 "${ETC}/checkout-relayer.env"
  install -m 0644 "${HERE}/systemd/sova-checkout-relayer.service" "${UNIT_DIR}/sova-checkout-relayer.service"
  systemctl daemon-reload
  if [[ -z "${CHECKOUT_ASHWINGS:-}" && -z "${CHECKOUT_RELAYER_CHECKOUT:-}" ]]; then
    systemctl disable --now sova-checkout-relayer >/dev/null 2>&1 || true
    log "checkout relayer installed, NOT started: no Ashwings recorded yet (deploy the contracts, then re-run deploy.sh)"
    return 0
  fi
  systemctl enable sova-checkout-relayer >/dev/null 2>&1
  if [[ ${changed} == 1 ]] || ! systemctl is-active --quiet sova-checkout-relayer; then
    systemctl restart sova-checkout-relayer
    log "checkout relayer (re)started on 127.0.0.1:${CHECKOUT_RELAYER_PORT} as ${addr} (fund it with SOVA: docs/ops/testnet-launch.md)"
  else
    log "checkout relayer unchanged and running (${addr})"
  fi
}

# ---- keeper ----------------------------------------------------------------------------
keeper_evm_address() {
  local init
  # stdout + stderr: the legacy-address warning goes to stderr.
  init="$(sudo -u sova-keeper /usr/local/bin/sova-miner --network test --data-dir "${DATA}/keeper" init 2>&1)"
  if [[ "${SOVA_SIP6}" == 1 ]] && grep -qE "LEGACY|not this key's own" <<<"${init}"; then
    # SIP-6 seals with the keystore key, so burns must credit that key's
    # own address. bin/sova would refuse the mismatch at start; fail here
    # first, with the fix. A fresh init always credits the key's own.
    printf '%s\n' "${init}" >&2
    die "the keeper's burns do not credit its own key's EVM address; SIP-6 needs them to (run: sudo -u sova-keeper sova-miner --network test --data-dir ${DATA}/keeper init --migrate-evm-address, then re-run deploy.sh; docs/ops/keeper-miner.md)"
  fi
  out keeper_taddr "$(awk '/t-addr to fund/ {print $NF}' <<<"${init}")"
  local evm
  evm="$(awk '/evm address/ {print $NF}' <<<"${init}")"
  out keeper_evm "${evm}"
  [[ "${evm}" =~ ^0x[0-9a-fA-F]{40}$ ]] || die "could not read the keeper's EVM address from sova-miner init"
  echo "${evm}"
}

# The keeper node's mode lines. SOVA_MINER_EVM_ADDRESS stays (it is what
# `sova-miner init` reports the burns credit): with SIP-6 on, bin/sova
# refuses to start unless it equals the sealing key's address, so the
# node can never seal as one address while burning for another.
keeper_mode_lines() { # evm
  printf 'SOVA_MINER_EVM_ADDRESS=%s\n' "$1"
  [[ "${SOVA_SIP6}" == 1 ]] && printf 'SOVA_SEALER_KEYSTORE=%s\n' "${SEALER_KEYSTORE}"
  return 0
}

# SIP-6: copy the keeper's miner keystore (sova-keeper's own 0600 file,
# which the burner keeps using) to the node's copy, 0600 and owned by sova,
# in a 0700 directory. Two files, each readable by exactly one service
# user. SEALER_KEY_CHANGED=1 if the copy changed (first install, or a
# re-init / migrate of the miner keystore), so the node restarts.
SEALER_KEY_CHANGED=0
install_sealer_key() {
  local src="${DATA}/keeper/keystore.json"
  [[ -s "${src}" ]] || die "no keeper keystore at ${src} (sova-miner init failed?)"
  install -d -m 0700 -o sova -g sova "$(dirname "${SEALER_KEYSTORE}")"
  if ! cmp -s "${src}" "${SEALER_KEYSTORE}"; then
    (umask 077 && install -m 0600 -o sova -g sova "${src}" "${SEALER_KEYSTORE}.new")
    mv -f "${SEALER_KEYSTORE}.new" "${SEALER_KEYSTORE}"
    SEALER_KEY_CHANGED=1
    log "sealing key installed at ${SEALER_KEYSTORE} (0600, sova)"
  fi
  chown sova:sova "${SEALER_KEYSTORE}"
  chmod 0600 "${SEALER_KEYSTORE}"
}

keeper_env_text() {
  cat <<EOF
ZEBRA_RPC_PORT=${ZEBRA_RPC_PORT}
KEEPER_PER_EPOCH_ZAT=${KEEPER_PER_EPOCH_ZAT:-10000}
KEEPER_BUDGET_ZAT=${KEEPER_BUDGET_ZAT:-35000000}
KEEPER_LIFETIME_BUDGET_ZAT=${KEEPER_LIFETIME_BUDGET_ZAT:-1000000000}
KEEPER_MIN_BURN_INTERVAL_SECS=${KEEPER_MIN_BURN_INTERVAL_SECS:-30}
EOF
}

setup_keeper() {
  local sum
  keeper_env_text >"${ETC}/keeper.env"
  install -m 0644 "${HERE}/systemd/sova-keeper.service" "${UNIT_DIR}/sova-keeper.service"
  systemctl daemon-reload
  # Never started here, but a burner that is already running is restarted
  # when its binary, budgets or unit changed; otherwise it keeps burning
  # with the old ones (2026-09-26: v0.1.8 was installed under a burner
  # still running v0.1.7).
  sum="$(cat /usr/local/bin/sova-miner "${ETC}/keeper.env" "${UNIT_DIR}/sova-keeper.service" | sha256sum | cut -d' ' -f1)"
  if keeper_paused; then
    log "sova-keeper NOT started or restarted: the keeper is paused (since $(paused_since), ${KEEPER_PAUSED_FILE}); ./deploy.sh keeper-resume"
  elif ! systemctl is-active --quiet sova-keeper; then
    log "sova-keeper installed, NOT started (publish the disclosure and fund the t-addr first; docs/ops/keeper-miner.md)"
  elif [[ "$(cat "${ETC}/.sova-keeper.sum" 2>/dev/null)" != "${sum}" ]]; then
    systemctl restart sova-keeper
    log "sova-keeper restarted (miner binary, budgets or unit changed)"
  else
    log "sova-keeper running, unchanged"
  fi
  echo "${sum}" >"${ETC}/.sova-keeper.sum"
}

# ---- cloudflared --------------------------------------------------------------------------
setup_cloudflared() {
  if ! command -v cloudflared >/dev/null 2>&1; then
    install -d -m 0755 /usr/share/keyrings
    curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg -o /usr/share/keyrings/cloudflare-main.gpg
    echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared ${VERSION_CODENAME} main" \
      >/etc/apt/sources.list.d/cloudflared.list
    apt-get update -qq && apt-get install -y -qq cloudflared >/dev/null
  fi
  install -m 0644 "${HERE}/systemd/cloudflared.service" "${UNIT_DIR}/cloudflared.service"
  systemctl daemon-reload
  systemctl enable cloudflared >/dev/null 2>&1
  if [[ -f "${ETC}/cloudflared.env" ]]; then
    systemctl restart cloudflared
    log "cloudflared running"
  else
    log "cloudflared installed; waiting for its token (cloudflare.sh tunnels)"
  fi
}

# ---- health ---------------------------------------------------------------------------------
health_env_text() {
  cat <<EOF
ROLE=${ROLE}
SOVA_EPOCH_BASE=${SOVA_EPOCH_BASE}
ZEBRA_RPC_PORT=${ZEBRA_RPC_PORT}
SOVA_HTTP_PORT=${SOVA_HTTP_PORT}
FAUCET_PORT=${FAUCET_PORT}
HEALTH_REFERENCE_RPC=${HEALTH_REFERENCE_RPC:-}
SOVA_SIP6=${SOVA_SIP6}
BLOCK_AGE_ALERT_MIN=${BLOCK_AGE_ALERT_MIN:-10}
NULL_SEALED_MAX_MIN=${NULL_SEALED_MAX_MIN:-45}
MEM_ALERT_MB=${MEM_ALERT_MB:-300}
KEEPER_ISOLATED_MIN=${KEEPER_ISOLATED_MIN:-5}
KEEPER_NODE_ID=${KEEPER_NODE_ID:-}
ZCASH_REFERENCE_URLS=${ZCASH_REFERENCE_URLS:-}
NU7_ACTIVATION_HEIGHT=${NU7_ACTIVATION_HEIGHT:-}
ZEBRA_IMAGE_DIGEST=${ZEBRA_IMAGE_DIGEST:-}
ZEBRA_READY_TIMEOUT_MIN=${ZEBRA_READY_TIMEOUT_MIN:-15}
ZEBRA_READY_LAG=${ZEBRA_READY_LAG:-3}
HEALTH_NETWORK_ALERTS=${HEALTH_NETWORK_ALERTS:-}
CHECKOUT_RELAYER_PORT=${CHECKOUT_RELAYER_PORT:-}
CHECKOUT_RELAYER_ALERT_BALANCE_WEI=${CHECKOUT_RELAYER_ALERT_BALANCE_WEI:-}
EOF
}

setup_health() {
  # health.sh (the timer), and the maintenance helpers for use by hand:
  # maint.sh (mute, keeper pause) and zebra-ready.sh.
  install -m 0755 "${HERE}/health.sh" "${HERE}/maint.sh" "${HERE}/zebra-ready.sh" /usr/local/lib/sova-infra/
  health_env_text >"${ETC}/host.env"
  chmod 0644 "${ETC}/host.env"
  install -m 0644 "${HERE}/systemd/sova-health.service" "${HERE}/systemd/sova-health.timer" "${UNIT_DIR}/"
  systemctl daemon-reload
  systemctl enable --now sova-health.timer >/dev/null 2>&1
}

# ---- no keys on public boxes (infra-m1 §4.1, M1 checklist) ------------------------------
check_no_keys() {
  case "${ROLE}" in
    seed | rpc)
      local found
      # -xdev per starting point: the root disk and the data volume.
      # sed -n 1,5p, not head -5: it reads to EOF, so find is never SIGPIPEd
      # into a silent set -e abort (pipefail) before the die below.
      found="$(find / "${DATA}" -xdev \( -name 'keystore*.json' -o -name 'miner.json' -o -name '*.keystore' \) \
        -not -path '/var/lib/docker/*' 2>/dev/null | sed -n 1,5p)"
      [[ -z "${found}" ]] || die "signing key material on a public ${ROLE} box: ${found}"
      [[ ! -d "${DATA}/faucet" && ! -d "${DATA}/keeper" && ! -d "${DATA}/sealer" ]] ||
        die "faucet/keeper/sealer state on a public ${ROLE} box"
      log "no-keys check passed (only the p2p node key and SSH host keys)"
      ;;
  esac
}

# --render: the files this host would get, written under $RENDER, using
# the same text functions as the real setup. Nothing is installed or run.
render_host() {
  install -d "${ETC}" "${UNIT_DIR}" "${SYSCTL_DIR}"
  swap_sysctl_text >"${SYSCTL_DIR}/${SWAP_SYSCTL_FILE}"
  log "$(swap_plan)"
  write_zebrad_files "$(zebra_ref)"
  cp "${HERE}/systemd/zebrad.service" "${HERE}/systemd/sova-health.service" \
    "${HERE}/systemd/sova-health.timer" "${UNIT_DIR}/"
  health_env_text >"${ETC}/host.env"
  if has_node; then
    local mode_lines="SOVA_FOLLOW_ONLY=1" rpc_profile=public
    if [[ "${ROLE}" == keeper ]]; then
      # The real value comes from `sova-miner init` on the host.
      mode_lines="$(keeper_mode_lines "0x<keeper-evm-from-sova-miner-init>")"
      rpc_profile=local
    fi
    node_env_text "${mode_lines}" "${rpc_profile}" >"${ETC}/sova-node.env"
    cp "${HERE}/systemd/sova-node.service" "${UNIT_DIR}/"
    [[ -z "${SOVA_EPOCH_BASE}" ]] || echo "${SOVA_EPOCH_BASE}" >"${ETC}/epoch-base-pinned"
  fi
  if [[ "${ROLE}" == faucet ]]; then
    faucet_toml_text >"${ETC}/faucet.toml"
    cp "${HERE}/systemd/sova-faucet.service" "${UNIT_DIR}/"
  fi
  if has_relayer; then
    # The key file is made on the host (keygen.mjs), never rendered.
    checkout_relayer_env_text >"${ETC}/checkout-relayer.env"
    cp "${HERE}/systemd/sova-checkout-relayer.service" "${UNIT_DIR}/"
  fi
  if [[ "${ROLE}" == keeper ]]; then
    keeper_env_text >"${ETC}/keeper.env"
    cp "${HERE}/systemd/sova-keeper.service" "${UNIT_DIR}/"
  fi
  has_tunnel && cp "${HERE}/systemd/cloudflared.service" "${UNIT_DIR}/"
  log "rendered into ${RENDER}"
}

if [[ -n "${RENDER}" ]]; then
  render_host
  exit 0
fi

mount_volume
setup_dirs
if [[ "${2:-}" == --enode-only ]]; then
  # deploy.sh's first pass: make (or read) the node key and print the
  # enode, so every node's bootnode list can be written before any starts.
  has_node && node_key_and_enode
  exit 0
fi
if [[ "${2:-}" == --zebra-only ]]; then
  # deploy.sh --zebra-only (a Zebra release, e.g. NU7): the health env first
  # (its new NU7_ACTIVATION_HEIGHT and the mute-aware health.sh), then
  # zebrad. No firewall, swap, binaries, sova-node, faucet, relayer, keeper
  # or cloudflared step, so none of them restarts.
  log "zebrad only on $(hostname) (${PUBLIC_IPV4}): $(zebra_ref)"
  setup_health
  setup_zebrad
  out zebra_image "$(zebra_ref)"
  log "done (zebrad only)"
  exit 0
fi
log "setting up ${ROLE} on $(hostname) (${PUBLIC_IPV4}), release ${SOVA_RELEASE_TAG}"
setup_ufw
setup_swap
setup_zebrad
install_binaries
[[ "${ROLE}" == keeper ]] && setup_keeper
has_node && setup_node
[[ "${ROLE}" == faucet ]] && setup_faucet
has_relayer && setup_checkout_relayer
has_tunnel && setup_cloudflared
setup_health
check_no_keys
out release "${SOVA_RELEASE_TAG}"
log "done"
